### PR TITLE
Load package description from README

### PR DESCRIPTION
**Pull request by prmtl**
To have a good formating of package description,
it was rewritten from Markdown to reStructuredText

Fixes: #145

### CODE REVIEW

**Comment by prmtl** [comment]
Preview of new description: https://test.pypi.org/project/test-of-pytdot/1.2.6/

**Comment by johnyf** [comment]
Thanks. However, I prefer Markdown, because it is easier to write and read in source form (e.g., there is a typo in the preview: "usin``g"). The [current long description on PyPI](https://pypi.org/project/pydot/1.2.3/) is not from the README, so it has good formatting. GitHub displays the Markdown README correctly.

Regarding #145, I now favor a simpler approach: to place the package's docstring within the script `setup.py`, as a short paragraph. Examples of packages that follow this simple approach are `networkx`, `numpy`, `scipy`, and `matplotlib`. Their "long" descriptions range from 1 line to a short paragraph. `pydot` follows the same approach, it is just that the description happened to be loaded from a module's docstring. This approach is independent of formatting, and encourages the reader to visit the repository in order to read the detailed README (which can be in Markdown).

Besides, I think that `warehouse` and other distribution infrastructure will eventually support Markdown, https://github.com/pypa/warehouse/issues/869.

**Comment by prmtl** [comment]
Fixed the typo.
I'm open to do it your way (just want #145 to be fixed), I just wanted to share my point with you:

>The current long description on PyPI is not from the README, so it has good formatting.

No, it doesn't. Line breaks are missing.

> GitHub displays the Markdown README correctly.

Just like ReST: https://github.com/prmtl/pydot/tree/fix/pythonoptimize_issue_145

> Regarding #145, I now favor a simpler approach: to place the package's docstring within the script setup.py, as a short paragraph. Examples of packages that follow this simple approach are networkx, numpy, scipy, and matplotlib. Their "long" descriptions range from 1 line to a short paragraph. pydot follows the same approach, it is just that the description happened to be loaded from a module's docstring. This approach is independent of formatting, and encourages the reader to visit the repository in order to read the detailed README (which can be in Markdown).

And then it is a bunch of packages (`httpie`, `requests`) that use README for this purpose. The plus is that you have just one source of package description. Also rich format like ReST or Markdown gives a nice way to include links, images, etc. into description on PyPI.

> Besides, I think that warehouse and other distribution infrastructure will eventually support Markdown, pypa/warehouse#869.

It seems that this will not happen in near future.

**Comment by johnyf** [comment]
Good point about the missing line breaks.

I didn't intend to suggest that GitHub doesn't render ReST, but that it does render Markdown, so that it currently works.

If the package description on PyPI is short, then it doesn't duplicate the information in the README. It is a high-level summary that remains usually unchanged between releases. In other words, the long description on PyPI doesn't need to be regarded as the README, it can be just an abstract.

Regarding the choice between ReST and Markdown, I find Markdown easier to write. This is a personal preference; others may find ReST easier.

**Comment by prmtl** [comment]
Updated.

**Comment by johnyf** [comment]
Thanks, but with `PYTHONOPTIMIZE=2` (#145), this change passes `None` as `long_description` to `setuptools.setup`. This can be observed using `print(__doc__)` inside `setup.py`.

Regarding PR branches, please avoid force pushing, as also [recommended for CPython](https://docs.python.org/devguide/pullrequest.html#submitting). Rebasing will be performed at the time of merging.

Other comments:

- The module `pydot` needs some docstring.
- The package's description does not describe the script `setup.py`.
- More changes needed to fully address #145 (f374f66b93ec7e6bb7a6812abdb2d8a62db879f8), i.e., behave compatibly with `PYTHONOPTIMIZE=2`.
- Mentioning issues from commits works better only after changes (e.g., in a PR) have been finalized. Otherwise it creates multiple copies of the same reference in the mentioned issue (when force pushing or amending), and also GitHub will retain those commits in the future, even if they were on some branch or fork and have been rebased or replaced. I have come to prefer documenting within issues which commits addressed them, after merging those to `master`.

Merged as of f374f66b93ec7e6bb7a6812abdb2d8a62db879f8

**Comment by johnyf** [comment]
[PyPI now supports Markdown READMEs](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi) (as anticipated [above](https://github.com/erocarrera/pydot/pull/160#issuecomment-335030514)).

**Pull request closed without merging**
